# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Usage
  items:
    - label: 'Install'
      link: '/install'
    - label: 'Configuration'
      link: '/configuration'
    - label: 'Getting started'
      link: '/getting-started'
- label: Topics
  items:
    - label: 'Ability Queue System'
      link: '/ability-queue-system'
    - label: 'Ignore Ability Cost'
      link: '/ignore-ability-cost'
    - label: 'Cheat Manager'
      link: '/cheat-manager'
- label: API
  items:
    - label: GSCCharacterBase
      link: /api/gsc-character-base
    - label: GSCPlayerState
      link: /api/gsc-player-state
    - label: GSCAbilitySystemComponent
      link: /api/gsc-ability-system-component
    - label: GSCGameplayAbility
      link: /api/gsc-gameplay-ability
    - label: GSCTask_PlayMontageWaitForEvent
      link: /api/gsc-task-play-montage-wait-for-event
    - label: GSCBlueprintFunctionLibrary
      link: /api/gsc-blueprint-function-library
    - label: GSCHUD
      link: /api/gschud
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Glossary
      link: /glossary
    - label: GASDocumentation
      link: https://github.com/tranek/GASDocumentation