# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Discord Server
  link: https://discord.gg/d4rs4vcX6t
- label: Installation
  items:
    - label: 'Install'
      link: '/install'
- label: Getting Started
  items:
    - label: 'Quick Start'
      link: '/quick-start'
    - label: 'ASC on Player State'
      link: '/asc-on-player-state'
    - label: 'Modular Game Features'
      link: '/getting-started/modular-game-features'
    - label: 'Launch Pad Window'
      link: '/launch-pad'
- label: 'Configuration'
  items:
    - label: 'Attribute Sets'
      link: '/configuration'
    - label: 'Gameplay Ability Definitions'
      link: '/config-ga-definitions'
    - label: 'Gameplay Effect Definitions'
      link: '/config-ge-definitions'
- label: 'Attributes'
  items:
    - label: 'Custom Gameplay Attributes'
      link: '/gameplay-attributes'
    - label: 'AttributeSet Events'
      link: '/attributeset-events'
- label: 'Abilities'
  items:
    - label: 'Melee Ability and Combo System'
      link: '/melee-ability'
    - label: 'Projectile Ability'
      link: '/projectile-ability'
- label: Topics
  items:
    - label: 'Ability Queue System'
      link: '/ability-queue-system'
    - label: 'Loosely Check Ability Cost'
      link: '/ignore-ability-cost'
    - label: 'Console Commands'
      link: '/cheat-manager'
    - label: 'Working with AI'
      link: '/working-with-ai'
    - label: 'Working with UI'
      link: '/working-with-ui'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
    - label: Additional Resource - GASDocumentation
      link: https://github.com/tranek/GASDocumentation