# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Discord Server
  link: https://discord.gg/d4rs4vcX6t
- label: More
  items:
    - label: Changelog
      link: /changelog
    - label: Additional Resource - GASDocumentation
      link: https://github.com/tranek/GASDocumentation