name: Eleventy Build
on:
  push:
    branches:
      - dev

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      # - name: Build
      #   uses: TartanLlama/actions-eleventy@master
      #   with:
      #     args: --config=.eleventy.cjs
      #     install_dependencies: true

      - name: Build eleventy
        run: |
          npx -y @11ty/eleventy --config=.eleventy.cjs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: public
          publish_branch: gh-pages
          external_repository: GASCompanion/GASCompanion.github.io
          personal_token: ${{ secrets.ACCESS_TOKEN }}
